SELECT B1_COD, B1_DESC, B1_UM, B1_TIPO,B1_POSIPI, BM_DESC FROM SB1990 AS  SB1
LEFT  JOIN SBM990 SBM ON SB1.B1_GRUPO = BM_GRUPO 
WHERE SB1.D_E_L_E_T_ = ' '-- AND B1_COD BETWEEN '' AND ''

SELECT B1_COD,B1_DESC,B1_UM,B1_TIPO,B1_POSIPI,BM_DESC FROM SB1990 SB1
 LEFT JOIN SBM990 SBM ON SB1.B1_GRUPO = BM_GRUPO 
 WHERE  SB1.D_E_L_E_T_= ' ' AND B1_COD BETWEEN '' AND 'zzzzzzz' 
  ORDER BY  B1_COD