#include 'TOTVS.CH'
#include 'Protheus.ch'


User Function zTFont()
Local oDlg1 //Variável que receberá a chamada da classe TDialog
Local cTituloJanela := "Bloqueador de Clientes"
Local oButton1 //Variável que armazenará a classe do primeiro botão(Se tornando um objeto)

Local oSay1, oSay2


Local cGet1 := Space(6)
Local oGet1

Local cGet2 := Space(2)
Local oGet2


oDlg1       := TDialog():New(0,0,500,500,cTituloJanela,,,,,CLR_BLACK,CLR_WHITE,,,.T.)
oSay1       := TSay():New(10,10,{||'Clientes'},oDlg1,,,,,,.T.,CLR_BLUE,CLR_WHITE,300,20)
oGet1       := TGet():New(25,10,{|u| IIF(Pcount()>0,cGet1:=u,cGet1)},oDlg1,40,10,"@!",,0,,,.F.,,.T.,,.F.,,.F.,.F.,,.F.,.F.,,cGet1,,,, )
oGet1:cF3   :="SA1"


oSay2       := TSay():New(10,60,{||'Clientes'},oDlg1,,,,,,.T.,CLR_BLUE,CLR_WHITE,300,20)
oGet2       := TGet():New(25,60,{|u| IIF(Pcount()>0,cGet2:=u,cGet2)},oDlg1,30,10,"@!",,0,,,.F.,,.T.,,.F.,,.F.,.F.,,.F.,.F.,,cGet1,,,, )
oButton1    := TButton():New(60, 10, "Bloquear agora",    oDlg1,{|| fBloq(cGet1,cGet2)}, 60,15,,,.F.,.T.,.F.,,.F.,,,.F. ) // Chama tela de Clientes



oDlg1:Activate(,,,.T.)
return 



Static Function fBloq(cCod,cLoja)

DbSelectArea("SA1")
SA1->(DbSeek(xFilial("SA1")+cCod+cLoja))//vai procurar o cliente e a loja que estao dentro dos gets 

RecLock("SA1",.F.)//true e inclusao e false e edicao alteracao
    SA1->A1_MSBLQL :='1'
MsUnlock()

MsgInfo("O cliente com codigo "+cCod+" e loja "+cLoja+" esta sendo bloqueado!", "Atencao")
Return 
